-- Hapus tabel lama jika ada (hati-hati, ini akan menghapus data!)
DROP VIEW IF EXISTS summary_view;
DROP TABLE IF EXISTS ledger_entries;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS categories;

-- 1. Buat tabel stores (Toko) menggantikan kategori sederhana
CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    whatsapp_number TEXT,
    maps_link TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Buat tabel produk (dengan relasi ke toko dan gambar)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Umum',
    price BIGINT NOT NULL,
    note TEXT,
    image_url TEXT,
    store_id BIGINT REFERENCES stores(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Buat tabel orders
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    shipping_cost BIGINT NOT NULL DEFAULT 0,
    subtotal BIGINT NOT NULL,
    total_amount BIGINT NOT NULL,
    note TEXT,
    shipping_address_link TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Buat tabel order items
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    line_total BIGINT NOT NULL
);

-- 5. Buat tabel ledger entries (buku kas)
CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    category TEXT NOT NULL,
    description TEXT,
    amount BIGINT NOT NULL,
    related_order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    happened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Buat index untuk pencarian cepat
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_ledger_entries_type ON ledger_entries(entry_type);
CREATE INDEX idx_products_store_id ON products(store_id);

-- 6. Buat View untuk Summary
CREATE VIEW summary_view AS
SELECT
    COALESCE(SUM(CASE WHEN entry_type = 'income' THEN amount ELSE 0 END), 0) AS total_income,
    COALESCE(SUM(CASE WHEN entry_type = 'expense' THEN amount ELSE 0 END), 0) AS total_expense,
    COALESCE(SUM(CASE WHEN entry_type = 'income' THEN amount ELSE 0 END), 0) -
    COALESCE(SUM(CASE WHEN entry_type = 'expense' THEN amount ELSE 0 END), 0) AS balance,
    (SELECT COUNT(*) FROM orders) AS total_orders,
    (SELECT COUNT(*) FROM products) AS product_count
FROM ledger_entries;

-- 7. Disable Row-Level Security (RLS)
-- Secara default Supabase mungkin mengaktifkan RLS yang memblokir akses insert/update.
-- Karena ini aplikasi pribadi tanpa fitur login, kita nonaktifkan RLS agar web bisa mengakses tabel.
ALTER TABLE stores DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries DISABLE ROW LEVEL SECURITY;

-- (Catatan: Storage dan Policy untuk gambar sudah dihapus dari script ini agar tidak error duplikasi)
